name: Vitor Baptista
description:
meta_description:

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "vendor", ".bundle"]

plugins: ["jekyll-paginate"]

permalink: /:title
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://vitorbaptista.com'
google_analytics: 'UA-2054412-1'

# Social networks
github: vitorbaptista
twitter: vitorbaptista
email: vitor@vitorbaptista.com
facebook: vitormbaptista
linkedin: vitorbaptista

# Details for the RSS feed generator
url:            'http://vitorbaptista.com'
author:         'Vitor Baptista'
author_bio: 'Software engineer passioned for civic hacking, free software, data visualization, and all the ways of improving our world through technology.'
