name: Vitor Baptista
description:
meta_description: "Your New Jekyll Site, Blogging about stuffs"

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "vendor", ".bundle"]

permalink: /:title
markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://vitorbaptista.com'
google_analytics: 'UA-2054412-1'

# Details for the RSS feed generator
url:            'http://vitorbaptista.com'
author:         'Vitor Baptista'
